ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from store import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('cart/', include('order.urls', namespace='cart')),
    path('', include('store.urls', namespace='store'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

store/urls.py
from django.urls import path
from . import views
from .models import Product
from .views import SubcategoryList, ProductDetail, GenderList

app_name = 'store'
urlpatterns = [
    path('<str:gender>/<str:subcategory>/<slug:slug>/', ProductDetail.as_view(), name='product-detail'),
    path('<str:gender>/<str:slug>/', SubcategoryList.as_view(), name='subcategory-product-list'),
    path('<str:gender>/', GenderList.as_view(), name='gender-category-list'),
    path('', views.IndexView.as_view(), name='home')
]

store/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django_countries.fields import CountryField
from django.conf import settings
from django.urls import reverse
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


GENDER_CHOICES = (
    ('unisex', 'Unisex'),
    ('male', 'Male'),
    ('female', 'Female')
)

LABEL_CHOISES= (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Brand(models.Model):
    name = models.CharField(max_length=250)
    description = models.CharField(max_length=250)
    slug = models.SlugField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    name = models.CharField(max_length=30)
    parent_category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                        null=True,
                                        blank=True, default=None, related_name='subcategory')
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10)
    description = models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Sub category'
        verbose_name_plural = 'Sub categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.gender, self.name])


class Size(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.name

    def color_tag(self):
        if self.code is not None:
            return mark_safe(f'<p style="background-color:{self.code}>{self.name}</p>"')
        else:
            return ''


def get_upload_path(instance, filename):
    return os.path.join(
      "%s" % instance.subcategory, "%s" % instance.slug, filename)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=200, db_index=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=200, db_index=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    image = models.ImageField(upload_to=get_upload_path, blank=True)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product-detail', args=[self.gender, self.subcategory, self.slug])

    def quantity(self):
        return ProductItem.objects.filter(product_id=self.id)


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, blank=True)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.title


class ProductItem(models.Model):
    name = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=1)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    image_id = models.ImageField(blank=True, null=True, default=0)
    on_sale = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.color} {self.name} size {self.size}'

    def image(self):
        img = Images.objects.get(image=self.image_id)
        if img.id:
            item_image = img.image.url
        else:
            item_image = ''
        return item_image

    def image_tag(self):
        img = Images.objects.get(id=self.image_id)
        if img.id:
            return mark_safe('<img src="{}" height="50"/>'.format(img.image.url))
        else:
            return ''


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    telephone = models.CharField(max_length=200)


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=200)
    apartment_address = models.CharField(max_length=200)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=10)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user

    class Meta:
        verbose_name_plural = 'Addresses'


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    # def __str__(self):
    #     return str(self.id)


class OrderItem(models.Model):
    product = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    street_address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    country = CountryField(multiple=False)
    zipcode = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.street_address

store/views.py
from urllib import request

from rest_framework import viewsets
from rest_framework import permissions
from django.http import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import View, TemplateView, ListView
from django.views.generic.detail import DetailView
from .models import Product, Category, SubCategory, GENDER_CHOICES, Brand, ProductItem, Size, Color
from .context_processors import static_categories
from order.models import ShoppingCartForm

from order.forms import CartAddProductForm

from store.serializers import ProductSerializer


class IndexView(TemplateView):
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class GenderList(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'store/gender_category_list.html'

    def get_queryset(self):
        gender = self.kwargs.get('gender')
        queryset = Product.objects.filter(gender=gender)
        if queryset:
            return queryset
        else:
            raise Http404


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_gender'] = self.kwargs.get('gender')
        context['genders'] = [gender[0] for gender in GENDER_CHOICES]
        context['brands'] = Brand.objects.all()
        context['colors'] = Color.objects.all()
        return context


class SubcategoryList(ListView):
    model = SubCategory
    context_object_name = 'products'
    template_name = 'store/subcategory_detail.html'

    def get_queryset(self):
        gender = self.kwargs.get('gender')
        subcategory = get_object_or_404(SubCategory, slug=self.kwargs.get('slug'))
        queryset = Product.objects.filter(subcategory__name=subcategory, gender=gender)
        if queryset:
            return queryset
        else:
            raise Http404

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['current_gender'] = self.kwargs.get('gender')
        context['genders'] = [gender[0] for gender in GENDER_CHOICES]
        context['subcategory'] = get_object_or_404(SubCategory, slug=self.kwargs.get('slug'))
        context['brands'] = Brand.objects.all()
        context['colors'] = Color.objects.all()
        return context


class ProductDetail(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'store/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = self.object
        context['genders'] = [gender[0] for gender in GENDER_CHOICES]
        context['current_gender'] = self.kwargs.get('gender')
        context['brands'] = Brand.objects.all()
        context['items'] = ProductItem.objects.filter(product_id=self.object.id)
        context['cart_product_form'] = CartAddProductForm()
        try:
            context['item_size'] = str(self.request.GET['size'])
            context['price'] = ProductItem.objects.get(product_id=self.object.id, size=Size.objects.get(name=context['item_size']))
        except MultiValueDictKeyError:
            pass
        return context

class ProductViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows products to be viewed or edited.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticated]

store/templates/store/base.html
{% load static %}
{% load filter_tags %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Obaju : e-commerce template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->

    <link rel="stylesheet" href="{% static 'store/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="{% static 'store/vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static 'store/vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'store/vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'store/css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'store/css/style.default.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header mb-5">
      <!--
      *** TOPBAR ***
      _________________________________________________________
      -->
      <div id="top">
        <div class="container">
          <div class="row">
            <div class="col-lg-6 offer mb-3 mb-lg-0"><a href="#" class="btn btn-success btn-sm">Offer of the day</a><a href="#" class="ml-1">Get flat 35% off on orders over $50!</a></div>
            <div class="col-lg-6 text-center text-lg-right">
              <ul class="menu list-inline mb-0">
                <li class="list-inline-item"><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
                <li class="list-inline-item"><a href="register.html">Register</a></li>
                <li class="list-inline-item"><a href="contact.html">Contact</a></li>
                <li class="list-inline-item"><a href="#">Recently viewed</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true" class="modal fade">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Customer login</h5>
                <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
              </div>
              <div class="modal-body">
                <form action="customer-orders.html" method="post">
                  <div class="form-group">
                    <input id="email-modal" type="text" placeholder="email" class="form-control">
                  </div>
                  <div class="form-group">
                    <input id="password-modal" type="password" placeholder="password" class="form-control">
                  </div>
                  <p class="text-center">
                    <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log in</button>
                  </p>
                </form>
                <p class="text-center text-muted">Not registered yet?</p>
                <p class="text-center text-muted"><a href="register.html"><strong>Register now</strong></a>! It is easy and done in 1 minute and gives you access to special discounts and much more!</p>
              </div>
            </div>
          </div>
        </div>
        <!-- *** TOP BAR END ***-->


      </div>
      <nav class="navbar navbar-expand-lg">
        <div class="container"><a href="index.html" class="navbar-brand home"><img src="img/logo.png" alt="Obaju logo" class="d-none d-md-inline-block"><img src="img/logo-small.png" alt="Obaju logo" class="d-inline-block d-md-none"><span class="sr-only">Obaju - go to homepage</span></a>
          <div class="navbar-buttons">
            <button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
            <button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></button><a href="basket.html" class="btn btn-outline-secondary navbar-toggler"><i class="fa fa-shopping-cart"></i></a>
          </div>
          <div id="navigation" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item"><a href="{% url 'store:home' %}" class="nav-link active">Home</a></li>
              {% for gender in genders %}{% if gender != 'unisex' %}
              <li class="nav-item dropdown menu-large"><a href="{% url  'store:gender-category-list' gender %}" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">{{ gender }}<b class="caret"></b></a>
                <ul class="dropdown-menu megamenu">
                  <li>
                    <div class="row">
                      {% for category in static_categories %}
                      <div class="col-md-6 col-lg-3">
                        <h5>{{ category.name }}</h5>
                        <ul class="list-unstyled mb-3">
                            {% subcategory_tag category.id gender as subcats %}
                            {% for subcat in subcats %}
                          <li class="nav-item"><a href="{% url 'store:subcategory-product-list' gender subcat.slug %}" class="nav-link">{{ subcat.name }}</a></li>
                            {% endfor %}
                        </ul>
                      </div>
                      {% endfor %}
                    </div>
                  </li>
                </ul>
              </li>
              {% endif %}
              {% endfor %}
<!--              <li class="nav-item dropdown menu-large"><a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link">Ladies<b class="caret"></b></a>-->
<!--                <ul class="dropdown-menu megamenu">-->
<!--                  <li>-->
<!--                    <div class="row">-->
<!--                      {% for category in static_categories %}-->
<!--                      <div class="col-md-6 col-lg-3">-->
<!--                        <h5>{{ category.name }}</h5>-->
<!--                        <ul class="list-unstyled mb-3">-->
<!--                            {% subcategory_tag category.id "female" as subcats %}-->
<!--                            {% for subcat in subcats %}-->
<!--                          <li class="nav-item"><a href="{% url 'store:subcategory-product-list' 'female' subcat.slug %}" class="nav-link">{{ subcat.name }}</a></li>-->
<!--                            {% endfor %}-->
<!--                        </ul>-->
<!--                      </div>-->
<!--                        {% endfor %}-->
<!--                    </div>-->
<!--                  </li>-->
<!--                </ul>-->
<!--              </li>-->
            </ul>
            <div class="navbar-buttons d-flex justify-content-end">
              <!-- /.nav-collapse-->
              <div id="search-not-mobile" class="navbar-collapse collapse"></div><a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></a>
              <div id="basket-overview" class="navbar-collapse collapse d-none d-lg-block"><a href="{% url 'order:cart_detail' %}" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i>
                {% with total_items=cart|length %}
                  {% if total_items > 0 %}
                <span>{{ total_items }} item{{ total_items|pluralize }} in cart ${{ cart.get_total_price }}{% else %}Cart is empty{% endif %}{% endwith %}</span></a></div>
            </div>
          </div>
        </div>
      </nav>
      <div id="search" class="collapse">
        <div class="container">
          <form role="search" class="ml-auto">
            <div class="input-group">
              <input type="text" placeholder="Search" class="form-control">
              <div class="input-group-append">
                <button type="button" class="btn btn-primary"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </header>
    <div id="all">
   {% block content %}
    {% endblock %}
    </div>
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Pages</h4>
            <ul class="list-unstyled">
              <li><a href="text.html">About us</a></li>
              <li><a href="text.html">Terms and conditions</a></li>
              <li><a href="faq.html">FAQ</a></li>
              <li><a href="contact.html">Contact us</a></li>
            </ul>
            <hr>
            <h4 class="mb-3">User section</h4>
            <ul class="list-unstyled">
              <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
              <li><a href="register.html">Regiter</a></li>
            </ul>
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Top categories</h4>
            <h5>Men</h5>
            <ul class="list-unstyled">
              <li><a href="category.html">T-shirts</a></li>
              <li><a href="category.html">Shirts</a></li>
              <li><a href="category.html">Accessories</a></li>
            </ul>
            <h5>Ladies</h5>
            <ul class="list-unstyled">
              <li><a href="category.html">T-shirts</a></li>
              <li><a href="category.html">Skirts</a></li>
              <li><a href="category.html">Pants</a></li>
              <li><a href="category.html">Accessories</a></li>
            </ul>
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Where to find us</h4>
            <p><strong>Obaju Ltd.</strong><br>13/25 New Avenue<br>New Heaven<br>45Y 73J<br>England<br><strong>Great Britain</strong></p><a href="contact.html">Go to contact page</a>
            <hr class="d-block d-md-none">
          </div>
          <!-- /.col-lg-3-->
          <div class="col-lg-3 col-md-6">
            <h4 class="mb-3">Get the news</h4>
            <p class="text-muted">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
            <form>
              <div class="input-group">
                <input type="text" class="form-control"><span class="input-group-append">
                  <button type="button" class="btn btn-outline-secondary">Subscribe!</button></span>
              </div>
              <!-- /input-group-->
            </form>
            <hr>
            <h4 class="mb-3">Stay in touch</h4>
            <p class="social"><a href="#" class="facebook external"><i class="fa fa-facebook"></i></a><a href="#" class="twitter external"><i class="fa fa-twitter"></i></a><a href="#" class="instagram external"><i class="fa fa-instagram"></i></a><a href="#" class="gplus external"><i class="fa fa-google-plus"></i></a><a href="#" class="email external"><i class="fa fa-envelope"></i></a></p>
          </div>
          <!-- /.col-lg-3-->
        </div>
        <!-- /.row-->
      </div>
      <!-- /.container-->
    </div>
    <!-- /#footer-->
    <!-- *** FOOTER END ***-->


    <!--
    *** COPYRIGHT ***
    _________________________________________________________
    -->
    <div id="copyright">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 mb-2 mb-lg-0">
            <p class="text-center text-lg-left">©2019 Your name goes here.</p>
          </div>
          <div class="col-lg-6">
            <p class="text-center text-lg-right">Template design by <a href="https://bootstrapious.com/">Bootstrapious</a>
              <!-- If you want to remove this backlink, pls purchase an Attribution-free License @ https://bootstrapious.com/p/obaju-e-commerce-template. Big thanks!-->
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- *** COPYRIGHT END ***-->
    <!-- JavaScript files-->
<!--    <script src="{% static 'store/vendor/jquery/jquery.min.js' %}"></script>-->
<!--    <script src="{% static 'store/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="{% static 'store/vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'store/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'store/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.js' %}"></script>
    <script src="{% static 'store/js/front.js' %}"></script>
  </body>
</html>

store/templates/store/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

store/templates/store/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

store/templates/store/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

store/templates/store/store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>