ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from store import views

router = routers.DefaultRouter()
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('cart/', include('order.urls', namespace='cart')),
    path('', include('store.urls', namespace='store'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

order/models.py
from django.contrib.auth.models import User

from django.db import models

from django.forms import ModelForm

from store.models import Product, ProductItem

from store.models import Size


class ShoppingCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    item = models.ForeignKey(ProductItem, on_delete=models.SET_NULL, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.item.name


    @property
    def price(self):
        return self.item.product.price

    @property
    def total(self):
        return self.quantity * self.item.product.price


class ShoppingCartForm(ModelForm):
    class Meta:
        model = ShoppingCart
        fields = ['quantity', 'size', 'item']

order/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(num, str(num)) for num in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

order/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.conf import settings
from .cart import Cart
from .forms import CartAddProductForm
from .models import ShoppingCart, ShoppingCartForm
# Create your views here.
from store.models import Product
import logging

from store.models import ProductItem

from store.models import Size


@require_POST
def cart_add(request, product_id):
    url = request.META.get('HTTP_REFERER')
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    if url.endswith('cart/'):
        product = get_object_or_404(ProductItem, id=product_id)
        size = product.size
        quantity = int(request.POST['quantity'])
        if form.is_valid():
            cart.add(product=product,
                     quantity=quantity,
                     size=size,
                     override_quantity=True)
        return redirect('order:cart_detail')
    else:
        size = request.POST['size']
        product = get_object_or_404(ProductItem, product_id=product_id, size=Size.objects.get(name=size))
        quantity = int(request.POST['quantity'])
        if form.is_valid():
            cart.add(product=product,
                     quantity=quantity,
                     size=size)
        return HttpResponseRedirect(url)

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(ProductItem, id=product_id)
    cart.remove(product)
    return redirect('order:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'order/detail.html', {'cart': cart})

order/templates/order/detail.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<div id="content">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <!-- breadcrumb-->
              <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li aria-current="page" class="breadcrumb-item active">Shopping cart</li>
                </ol>
              </nav>
            </div>
            <div id="basket" class="col-lg-9">
              <div class="box">
                  <h1>Shopping cart</h1>
                  <p class="text-muted">{% with total_items=cart|length %}
                  {% if total_items > 0 %}
                <span>{{ total_items }} item{{ total_items|pluralize }} in cart ${{ cart.get_total_price }}{% else %}Cart is empty{% endif %}{% endwith %}</p>
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th colspan="2">Product</th>
                          <th>Size</th>
                          <th>Quantity</th>
                          <th>Unit price</th>
                          <th>Discount</th>
                          <th colspan="2">Total</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for item in cart %}
                        {% with product=item.product %}
                        <tr>
                          <td><a href="{{ product.get_absolute_url }}">
                              <img src="{% if product.image_id %}{{ product.image_id.url }}
                            {% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}"></a>
                          </td>
                          <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                          <td>
                            {{ product.size }}
                          </td>
                          <td>
                              <form id="quantity{{ product.js }}" action="{% url 'cart:cart_add' product.id %}" method="post">
                                  <input onclick="form.submit()" name="quantity{{ product.js }}" type="number" value="{{ item.quantity }}" class="form-control">
                                  {% csrf_token %}
                              </form>
                          </td>
                          <td>$ {{ item.price }}</td>
                          <td>$0.00</td>
                          <td>$ {{ item.total_price }}</td>
                            <td>
                                        <form action="{% url 'order:cart_remove' product.id %}" method="post">
                                           <button type="submit" class="btn btn-outline-secondary"><i type="submit" class="fa fa-trash-o"></i></button>
                                            {% csrf_token %}
                                        </form>
                            </td>
                        </tr>
                        {% endwith %}
                      {% endfor %}
                      </tbody>
                      <tfoot>
                        <tr>
                          <th colspan="5">Total</th>
                          <th colspan="2">${{ cart.get_total_price }}</th>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                  <!-- /.table-responsive-->
                  <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                    <div class="left"><a href="category.html" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue shopping</a></div>
                    <div class="right">
<!--                      <button type="submit"  class="btn btn-outline-secondary"><i class="fa fa-refresh"></i> Update cart</button>-->
                      <button type="submit" class="btn btn-primary">Proceed to checkout <i class="fa fa-chevron-right"></i></button>
                    </div>
                  </div>
              </div>
              <!-- /.box-->
              <div class="row same-height-row">
                <div class="col-lg-3 col-md-6">
                  <div class="box same-height">
                    <h3>You may also like these products</h3>
                  </div>
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="product same-height">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href="detail.html"><img src="img/product2.jpg" alt="" class="img-fluid"></a></div>
                        <div class="back"><a href="detail.html"><img src="img/product2_2.jpg" alt="" class="img-fluid"></a></div>
                      </div>
                    </div><a href="detail.html" class="invisible"><img src="img/product2.jpg" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3>Fur coat</h3>
                      <p class="price">$143</p>
                    </div>
                  </div>
                  <!-- /.product-->
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="product same-height">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href="detail.html"><img src="img/product1.jpg" alt="" class="img-fluid"></a></div>
                        <div class="back"><a href="detail.html"><img src="img/product1_2.jpg" alt="" class="img-fluid"></a></div>
                      </div>
                    </div><a href="detail.html" class="invisible"><img src="img/product1.jpg" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3>Fur coat</h3>
                      <p class="price">$143</p>
                    </div>
                  </div>
                  <!-- /.product-->
                </div>
                <div class="col-md-3 col-sm-6">
                  <div class="product same-height">
                    <div class="flip-container">
                      <div class="flipper">
                        <div class="front"><a href="detail.html"><img src="img/product3.jpg" alt="" class="img-fluid"></a></div>
                        <div class="back"><a href="detail.html"><img src="img/product3_2.jpg" alt="" class="img-fluid"></a></div>
                      </div>
                    </div><a href="detail.html" class="invisible"><img src="img/product3.jpg" alt="" class="img-fluid"></a>
                    <div class="text">
                      <h3>Fur coat</h3>
                      <p class="price">$143</p>
                    </div>
                  </div>
                  <!-- /.product-->
                </div>
              </div>
            </div>
            <!-- /.col-lg-9-->
            <div class="col-lg-3">
              <div id="order-summary" class="box">
                <div class="box-header">
                  <h3 class="mb-0">Order summary</h3>
                </div>
                <p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>
                <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Order subtotal</td>
                        <th>{{ cart.get_total_price }}</th>
                      </tr>
                      <tr>
                        <td>Shipping and handling</td>
                        <th>$10.00</th>
                      </tr>
                      <tr>
                        <td>Tax</td>
                        <th>$0.00</th>
                      </tr>
                      <tr class="total">
                        <td>Total</td>
                        <th>${{ cart.get_total_price }}</th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="box">
                <div class="box-header">
                  <h4 class="mb-0">Coupon code</h4>
                </div>
                <p class="text-muted">If you have a coupon code, please enter it in the box below.</p>
                <form>
                  <div class="input-group">
                    <input type="text" class="form-control"><span class="input-group-append">
                      <button type="button" class="btn btn-primary"><i class="fa fa-gift"></i></button></span>
                  </div>
                  <!-- /input-group-->
                </form>
              </div>
            </div>
            <!-- /.col-md-3-->
          </div>
        </div>
      </div>
{% endblock %}